// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/1/2025, 11:22:19 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/swiz/Other/lab6/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/swiz/Other/lab6/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/swiz/Other/lab6/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/swiz/Other/lab6/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/swiz/Other/lab6/plugins/**/*.{js,ts,mjs}","/home/swiz/Other/lab6/composables/**/*.{js,ts,mjs}","/home/swiz/Other/lab6/utils/**/*.{js,ts,mjs}","/home/swiz/Other/lab6/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/swiz/Other/lab6/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/swiz/Other/lab6/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;