// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/27/2025, 10:43:49 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/swiz/Other/nuxtmod/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/swiz/Other/nuxtmod/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/swiz/Other/nuxtmod/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/swiz/Other/nuxtmod/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/swiz/Other/nuxtmod/plugins/**/*.{js,ts,mjs}","/home/swiz/Other/nuxtmod/composables/**/*.{js,ts,mjs}","/home/swiz/Other/nuxtmod/utils/**/*.{js,ts,mjs}","/home/swiz/Other/nuxtmod/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/swiz/Other/nuxtmod/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/swiz/Other/nuxtmod/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;